Strict Parsing Decimal Documentation
AbsaOSS/enceladus pull request #1524
Opened 2020-09-17 14:09 UTC by AdrianOlosutean

2020-09-17 15:31 UTC, zakera786 approved these changes

2020-09-17 16:39 UTC, benedeki requested changes

2020-09-17 16:39 UTC, benedeki commented on _docs/2.0.0/usage/schema.md
> +| [strict_parsing](#strict_parsing)         | decimal                     | Flat indicating strict parsing on the provided decimal value. Strict parsing rejects a value(including default) with a larg
```suggestion
| [strict_parsing](#strict_parsing)         | decimal                     | Flag indicating if strict parsing should be done on the input value. Strict parsing rejects a value with a more decimal value than the defined scale of the decimal       | *true*          | *false*                                      |
```

2020-09-17 16:39 UTC, benedeki commented on _docs/2.0.0/usage/schema.md
> +longer scale(like 10.12345, 0.1234) will rejected
```suggestion
Strict parsing rejects a value with more decimal places than the scale (second number) of the field's Decimal type definition. 
This results in a casting error in error column ([see here]({{ site.baseurl }}/docs/{{ page.version }}/usage-errcol)). For example for Decimal(X,2), the values with
longer scale (like 10.12345, 0.1234) will be rejected .
Default value have to fit the scale as well in the case of strict parsing.
```

2020-09-17 16:39 UTC, benedeki commented on _docs/2.0.0/usage/schema.md
> +- If 'strict_parsing' is enabled for [`Decimal`](#decimal), the decimal scale should fit into the specified type scale
```suggestion
- If 'strict_parsing' is enabled for [`Decimal`](#decimal), the number of decimal places has to fit into the type's scale
```

2020-09-18 08:41 UTC, AdrianOlosutean commented on _docs/2.0.0/usage/schema.md
> +Flat indicating strict parsing on the provided decimal value.
`Exercised` sounds weird for me. I would say `applied`

2020-09-18 08:57 UTC, benedeki commented on _docs/2.0.0/usage/schema.md
> +Flat indicating strict parsing on the provided decimal value.
Applied it good 👍

2020-09-18 11:46 UTC, benedeki commented on _docs/2.0.0/usage/schema.md
> +| [strict_parsing](#strict_parsing)         | decimal                     | Flag indicating if strict parsing should be done on the input value. Strict parsing rejects a value with a higher decimal v
```suggestion
| [strict_parsing](#strict_parsing)         | decimal                     | Flag indicating if strict parsing should be done on the input value. Strict parsing rejects a value with more decimal places than the defined scale     | *true*          | *false*                                      |
```
Sorry, the previous suggestion didn't make sense there.

2020-09-18 15:01 UTC, benedeki approved these changes

2020-09-18 18:09 UTC, merged