#1853: Remove the warning of wrong browser type and version in Menas
AbsaOSS/enceladus pull request #1854
Opened 2021-07-17 10:16 UTC by benedeki

Release notes suggestion:
Warning if other then Chrome browser used for Menas removed.

2021-07-19 11:52 UTC, dk1844 approved these changes
- [x] code reviewed
- [x] pulled
- [x] built
- [x] run

LGTM, works as expected.

2021-07-19 13:32 UTC, AdrianOlosutean submitted a review, later dismissed

2021-07-23 00:15 UTC, benedeki commented
Put the warning back, but little more elaborate. Would welcome a test on Safari.

2021-07-23 07:35 UTC, AdrianOlosutean requested changes
I will test safari too

2021-07-23 07:35 UTC, AdrianOlosutean commented on menas/ui/components/login/loginDetail.controller.js
> +        sap.m.MessageBox.warning("Chrome browser version lower then 68 is known of having issue displaying the Menas application");
```suggestion
        sap.m.MessageBox.warning("Chrome browser version lower than 68 is known of having issue displaying the Menas application");
```

2021-07-23 07:35 UTC, AdrianOlosutean commented on menas/ui/components/login/loginDetail.controller.js
> +        sap.m.MessageBox.warning("Firefox browser version lower then 78 is known of having issue displaying the Menas application");
```suggestion
        sap.m.MessageBox.warning("Firefox browser version lower than 78 is known of having issue displaying the Menas application");
```

2021-07-23 07:35 UTC, AdrianOlosutean commented on menas/ui/components/login/loginDetail.controller.js
> +        sap.m.MessageBox.warning("Edge browser version lower then 79 is known of having issue displaying the Menas application");
```suggestion
        sap.m.MessageBox.warning("Edge browser version lower than 79 is known of having issue displaying the Menas application");
```

2021-07-23 07:35 UTC, AdrianOlosutean commented on menas/ui/components/login/loginDetail.controller.js
> +        sap.m.MessageBox.warning("Safari browser version lower then 12 is known of having issue displaying the Menas application");
```suggestion
        sap.m.MessageBox.warning("Safari browser version lower than 12 is known of having issue displaying the Menas application");
```

2021-07-23 12:28 UTC, AdrianOlosutean approved these changes
Tested with a higher version of Safari and no warning

2021-07-23 14:50 UTC, Zejnilovic approved these changes

2021-07-23 19:47 UTC, merged