Merge/merging release 2.25 into develop ver 3
AbsaOSS/enceladus pull request #1963
Opened 2021-10-26 14:55 UTC by dk1844

- locally & on-Jenkins buildable
### Testrun
 - has been test-run with `-Dspline.mode=DISABLED`, but since there haven't been spline updates, it should be a problem.

2021-11-01 16:17 UTC, AdrianOlosutean reviewed
Just some small things

2021-11-01 16:17 UTC, AdrianOlosutean commented on rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/DatasetApiIntegrationSuite.scala
> +import za.co.absa.enceladus.model.conformanceRule.MappingConformanceRule
Dulplicates

2021-11-01 16:17 UTC, AdrianOlosutean commented on rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/repositories/DatasetRepositoryIntegrationSuite.scala
> +import za.co.absa.enceladus.model.Dataset
Duplicate

2021-11-01 16:17 UTC, AdrianOlosutean commented on rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/repositories/StatisticsIntegrationSuite.scala
> +import za.co.absa.enceladus.rest_api.repositories.{DatasetMongoRepository, PropertyDefinitionMongoRepository}
Not needed

2021-11-02 08:25 UTC, AdrianOlosutean requested changes

2021-11-02 08:25 UTC, AdrianOlosutean commented on menas/ui/service/PropertiesService.js
> +    return RestClient.get(`api/properties/datasets/${propertyName}`);
This is breaking
```suggestion
    return RestClient.get(`properties/datasets/${propertyName}`);
```

2021-11-02 08:49 UTC, dk1844 commented on menas/ui/service/PropertiesService.js
> +    return RestClient.get(`api/properties/datasets/${propertyName}`);
Thanks for noticing!

2021-11-02 10:25 UTC, dk1844 commented on rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/controllers/DatasetApiIntegrationSuite.scala
> +import za.co.absa.enceladus.model.conformanceRule.MappingConformanceRule
Removed, thanks for noticing.

2021-11-02 10:25 UTC, dk1844 commented on rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/repositories/DatasetRepositoryIntegrationSuite.scala
> +import za.co.absa.enceladus.model.Dataset
import za.co.absa.enceladus.rest_api.repositories.{DatasetMongoRepository, PropertyDefinitionMongoRepository}

2021-11-02 10:25 UTC, dk1844 commented on rest-api/src/test/scala/za/co/absa/enceladus/rest_api/integration/repositories/StatisticsIntegrationSuite.scala
> +import za.co.absa.enceladus.rest_api.repositories.{DatasetMongoRepository, PropertyDefinitionMongoRepository}
Removed, thanks for noticing.

2021-11-03 14:22 UTC, AdrianOlosutean approved these changes
Tested locally, looks good

2021-11-04 09:09 UTC, merged